### ISSUE TITLE
dotnet.yml Bug Report

### ISSUE THREAD

**Issue by evlyou666** [WorldBalancer/World_Balancer_logger#8]
Here are some potential issues with the provided GitHub Actions workflow:

1. The `dotnet-version` specified in the `actions/setup-dotnet@v3` action is `7.0.x`, but as of the time of this writing, .NET 7.0 has not been released yet. The latest stable version is 6.0.302, so you may want to update the version number accordingly.
2. The `dotnet restore` command in the `Restore dependencies` step should be sufficient to restore dependencies without the need for the `--no-restore` flag in the `Build` step. This flag tells the `dotnet build` command to restore dependencies before building, but since `dotnet restore` was already called in the previous step, it's not necessary.
3. Similarly, the `--no-build` flag in the `Test` step is not necessary if you want to build the project before testing. If you want to build and test in separate steps, you should consider using the `dependsOn` key in the `Test` step to ensure that it only runs after the `Build` step has completed successfully.
4. The `verbosity` option in the `dotnet test` command is set to `normal`, but it can also be set to `quiet`, `minimal`, `normal`, `detailed`, or `diagnostic`. You may want to adjust the verbosity level based on your testing needs.

Here's an updated version of the workflow that addresses these issues:

```yaml
name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --verbosity normal
      dependsOn: build
```

Note that I've
